name       : perl-test-memory-cycle
version    : 1.06
release    : 6
source     :
    - https://cpan.metacpan.org/authors/id/P/PE/PETDANCE/Test-Memory-Cycle-1.06.tar.gz : 9d53ddfdc964cd8454cb0da4c695b6a3ae47b45839291c34cb9d8d1cfaab3202
license    : Artistic-2.0
component  : programming.perl
summary    : Test::Memory::Cycle - Check for memory leaks and circular memory references
description: |
    Test::Memory::Cycle -- A Perl module to check for memory leaks and circular memory references.
builddeps  :
    - perl-devel-cycle
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
